### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'.

### ISSUE THREAD

**Issue by KvizadSaderah** [lusob/maiker-cli#5]
Running example on macOS, got this error

```
maiker "a snake game using just html and js"; open maiker-generated-project/index.html
Generating code project from prompt: a snake game using just html and js

Traceback (most recent call last):
  File "/usr/local/bin/maiker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/maiker/cli.py", line 69, in main
    generated_code = generate_project(prompt)
  File "/usr/local/lib/python3.10/site-packages/maiker/cli.py", line 26, in generate_project
    completion = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?
The file /Users/dmitriyefremov/maiker-generated-project/index.html does not exist.
```

**Comment by lusob** [comment]
It looks you have an old version of openai installed, try to update it
Similar issue: https://github.com/openai/openai-python/issues/246
